UdemyNLayer_Project/UdemyNLayer_Project.Web/Models/ErrorViewModel.cs
using System;

namespace UdemyNLayer_Project.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UdemyNLayer_Project/UdemyNLayer_Project.Web/Controllers/CategoriesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UdemyNLayer_Project.Web.APIService;
using UdemyNLayer_Project.Web.DTOs;

namespace UdemyNLayer_Project.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly CategoryAPIService _categoryAPIService;
        private readonly IMapper _mapper;
        public CategoriesController(IMapper mapper, CategoryAPIService categoryAPIService)
        {
            this._categoryAPIService = categoryAPIService;
            this._mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await _categoryAPIService.GetAllAsync();

            return View(categories);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CategoryDto categoryDto)
        {
            await _categoryAPIService.AddAsync(categoryDto);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int id)
        {
            var category = await _categoryAPIService.GetByIdAsync(id);

            return View(category);
        }
        [HttpPost]
        public async Task<IActionResult> Update(CategoryDto categoryDto)
        {
            await _categoryAPIService.Update(categoryDto);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _categoryAPIService.Remove(id);

            return RedirectToAction("Index");
        }
    }
}

UdemyNLayer_Project/UdemyNLayer_Project.Web/Controllers/CoursesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UdemyNLayer_Project.Web.APIService;
using UdemyNLayer_Project.Web.DTOs;

namespace UdemyNLayer_Project.Web.Controllers
{
    public class CoursesController : Controller
    {
        private readonly CourseAPIService _courseAPIService;
        private readonly CategoryAPIService _categoryAPIService;
        private readonly InstructorAPIService _instructorAPIService;
        private readonly IMapper _mapper;
        public CoursesController(CourseAPIService courseAPIService, InstructorAPIService instructorAPIService, CategoryAPIService categoryAPIService, IMapper mapper)
        {
            this._courseAPIService = courseAPIService;
            this._categoryAPIService = categoryAPIService;
            this._instructorAPIService = instructorAPIService;
            this._mapper = mapper;
        }
        public void categoryList()
        {
            List<SelectListItem> categoryList = (from x in _categoryAPIService.GetAllAsync().Result
                                                 select new SelectListItem
                                                 {
                                                     Text = x.Name,
                                                     Value = x.Id.ToString()
                                                 }).ToList();

            ViewBag.categoryList = categoryList;
        }
        public void instructorList()
        {
            List<SelectListItem> instructorList = (from x in _instructorAPIService.GetAllAsync().Result
                                                   select new SelectListItem
                                                   {
                                                       Text = x.Name + " " + x.Surname,
                                                       Value = x.Id.ToString()
                                                   }).ToList();

            ViewBag.instructorList = instructorList;
        }
        public async Task<IActionResult> Index()
        {
            var courses = await _courseAPIService.GetAllAsync();

            categoryList();
            instructorList();

            return View(courses);
        }
        public IActionResult Create()
        {
            categoryList();
            instructorList();

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CourseDto courseDto)
        {
            await _courseAPIService.AddAsync(courseDto);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int id)
        {
            var course = await _courseAPIService.GetByIdAsync(id);

            categoryList();
            instructorList();

            return View(course);
        }
        [HttpPost]
        public async Task<IActionResult> Update(CourseDto courseDto)
        {
            await _courseAPIService.Update(courseDto);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _courseAPIService.Remove(id);

            return RedirectToAction("Index");
        }
    }
}

UdemyNLayer_Project/UdemyNLayer_Project.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using UdemyNLayer_Project.Web.Models;

namespace UdemyNLayer_Project.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UdemyNLayer_Project/UdemyNLayer_Project.Web/Controllers/InstructorsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UdemyNLayer_Project.Web.APIService;
using UdemyNLayer_Project.Web.DTOs;

namespace UdemyNLayer_Project.Web.Controllers
{
    public class InstructorsController : Controller
    {
        private readonly InstructorAPIService _instructorAPIService;
        public InstructorsController(InstructorAPIService instructorAPIService)
        {
            this._instructorAPIService = instructorAPIService;
        }
        public async Task<IActionResult> Index()
        {
            var instructors = await _instructorAPIService.GetAllAsync();

            return View(instructors);
        }
        public async Task<IActionResult> IndexWithCourses(int id)
        {
            var instructorsWithCourses = await _instructorAPIService.GetWithCourseById(id);

            return View(instructorsWithCourses);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(InstructorDto instructorDto)
        {
            await _instructorAPIService.AddAsync(instructorDto);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int id)
        {
            var instructor = await _instructorAPIService.GetByIdAsync(id);

            return View(instructor);
        }
        [HttpPost]
        public async Task<IActionResult> Update(InstructorDto instructorDto)
        {
            await _instructorAPIService.Update(instructorDto);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _instructorAPIService.Remove(id);

            return RedirectToAction("Index");
        }
    }
}

UdemyNLayer_Project/UdemyNLayer_Project.Web/Views/Courses/Create.cshtml
@model CourseDto
@{
    ViewData["Title"] = "Create";
}

<figure class="text-center">
    <blockquote class="blockquote">
        <h2>Categories</h2>
    </blockquote>
    <figcaption class="blockquote-footer mt-1">
        Is the new category add page.
    </figcaption>
</figure>

<div class="container">
    <div class="row">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" type="text" class="form-control col-md-12" aria-describedby="emailHelp">
                <span asp-validation-for="Name"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Description" class="form-label">Description</label>
                @Html.TextAreaFor(x => x.Description, new { @class = "form-control col-md-12", rows = "4", cols = "4" })
                <span asp-validation-for="Description"></span>
            </div>

            <label asp-for="Price" class="form-label">Price</label>
            <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input asp-for="Price" type="text" class="form-control col-md-12" />
                <span class="input-group-text">.00</span>
                <span asp-validation-for="Price"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Course_Hour" class="form-label">Course Hour</label>
                <input asp-for="Course_Hour" type="text" class="form-control col-md-12" aria-describedby="emailHelp">
                <span asp-validation-for="Course_Hour"></span>
            </div>

            <div class="mb-3">
                <label asp-for="InstructorId" class="form-label">Instructor</label>
                @Html.DropDownListFor(x => x.InstructorId, (List<SelectListItem>)ViewBag.instructorList, new { @class = "form-control col-md-12" })
                <span asp-validation-for="InstructorId"></span>
            </div>

            <div class="mb-3">
                <label asp-for="CategoryId" class="form-label">Category</label>
                @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.categoryList, new { @class = "form-control col-md-12" })
                <span asp-validation-for="CategoryId"></span>
            </div>

            <button type="submit" class="btn btn-primary btn-sm">Create</button>
        </form>
    </div>
</div>

UdemyNLayer_Project/UdemyNLayer_Project.Web/Views/Courses/Index.cshtml
@model IEnumerable<CourseDto>
@{
    ViewData["Title"] = "Course Index";
}

<figure class="text-center">
    <blockquote class="blockquote">
        <h2>Courses</h2>
    </blockquote>
    <figcaption class="blockquote-footer mt-1">
        Page with category information.
    </figcaption>
    <div class="text-center">
        <a class="mb-3" asp-action="Create" style="text-decoration:none;">New Courses</a>
    </div>
</figure>

<div class="container">
    <div class="col align-self-center">

        <div id="carouselExampleCaptions" class="carousel carousel-dark slide my-3" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://i.hizliresim.com/7a8299t.PNG" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>First slide label</h5>
                        <p>Some representative placeholder content for the first slide.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="https://i.hizliresim.com/7a8299t.PNG" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Second slide label</h5>
                        <p>Some representative placeholder content for the second slide.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="https://i.hizliresim.com/7a8299t.PNG" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Third slide label</h5>
                        <p>Some representative placeholder content for the third slide.</p>
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>

        <div class="row row-cols-1 row-cols-md-2 g-4 mt-2">
            @foreach (var course in Model)
            {
            <div class="col-sm-6">
                <div class="card border-0">
                    <img class="card-img-top text-center" src="@course.Course_ImageUrl" style="width:450px; height:225px;">
                    <div class="card-body">
                        <div style="max-width:440px;">
                            <h5 class="card-title">@course.Name</h5>
                            <p class="card-text">@course.Description</p>
                        </div>
                        <p class="mt-2"><strong>@(course.Price + " TL")</strong></p>
                        <p class="card-text">
                            <small class="text-muted">
                                @(course.Course_Hour + " Saat | Tüm Düzeyler | ")
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill mb-1" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                </svg>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill mb-1" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                </svg>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill mb-1" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                </svg>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill mb-1" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                </svg>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-half mb-1" viewBox="0 0 16 16">
                                    <path d="M5.354 5.119 7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.548.548 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.52.52 0 0 1-.146.05c-.342.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.172-.403.58.58 0 0 1 .085-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027a.5.5 0 0 1 .232.056l3.686 1.894-.694-3.957a.565.565 0 0 1 .162-.505l2.907-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.001 2.223 8 2.226v9.8z" />
                                </svg>
                            </small>
                        </p>
                    </div>
                </div>
                <div>
                    <a class="btn btn-outline-success btn-sm" style="margin-left:11em;" asp-action="Update" asp-route-id="@course.Id">Update</a>
                    <a class="btn btn-outline-danger btn-sm" asp-action="Delete" asp-route-id="@course.Id">Delete</a>
                </div>
                <hr style="width:500px;" />
            </div>
            }
        </div>
    </div>
</div>

UdemyNLayer_Project/UdemyNLayer_Project.Web/Views/Courses/Update.cshtml
@model CourseDto
@{
    ViewData["Title"] = "Update";
}

<figure class="text-center">
    <blockquote class="blockquote">
        <h2>Courses</h2>
    </blockquote>
    <figcaption class="blockquote-footer mt-1">
        Update existing category page.
    </figcaption>
</figure>

<div class="container">
    <div class="row">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Name"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Description" class="form-label">Description</label>
                @Html.TextAreaFor(x => x.Description, new { @class = "form-control col-md-6", rows = "4", cols = "4" })
                <span asp-validation-for="Description"></span>
            </div>

            <label asp-for="Price" class="form-label">Price</label>
            <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input asp-for="Price" type="text" class="form-control col-md-6" />
                <span class="input-group-text">.00</span>
                <span asp-validation-for="Price"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Course_Hour" class="form-label">Course Hour</label>
                <input asp-for="Course_Hour" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Course_Hour"></span>
            </div>

            <div class="mb-3">
                <label asp-for="InstructorId" class="form-label">Instructor</label>
                @Html.DropDownListFor(x => x.InstructorId, (List<SelectListItem>)ViewBag.instructorList, new { @class = "form-control col-md-6" })
                <span asp-validation-for="InstructorId"></span>
            </div>

            <div class="mb-3">
                <label asp-for="CategoryId" class="form-label">Category</label>
                @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.categoryList, new { @class = "form-control col-md-6" })
                <span asp-validation-for="CategoryId"></span>
            </div>

            <button type="submit" class="btn btn-primary btn-sm">Update</button>
        </form>
    </div>
</div>

UdemyNLayer_Project/UdemyNLayer_Project.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UdemyNLayer_Project/UdemyNLayer_Project.Web/Views/Instructors/Create.cshtml
@model InstructorDto
@{
    ViewData["Title"] = "Create";
}

<figure class="text-center">
    <blockquote class="blockquote">
        <h2>Instructors</h2>
    </blockquote>
    <figcaption class="blockquote-footer mt-1">
        Is the new instructor add page.
    </figcaption>
</figure>

<div class="container">
    <div class="row">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Name"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Surname" class="form-label">Surname</label>
                <input asp-for="Surname" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Surname"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Telephone" class="form-label">Telephone</label>
                <input asp-for="Telephone" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Telephone"></span>
            </div>

            <div class="mb-3">
                <label asp-for="About" class="form-label">Description</label>
                @Html.TextAreaFor(x => x.About, new { @class = "form-control col-md-6", rows = "4", cols = "4" })
                <span asp-validation-for="About"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Degree" class="form-label">Degree</label>
                <input asp-for="Degree" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Degree"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Mail" class="form-label">Mail</label>
                <input asp-for="Mail" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Mail"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Password" class="form-label">Password</label>
                <input asp-for="Password" id="myPassword" type="password" class="form-control col-md-6" aria-describedby="emailHelp">
                <div class="form-check mt-1">
                    <input class="form-check-input" type="checkbox" onclick="myFunction()">
                    <label class="form-check-label" for="flexCheckDefault">
                        Show Password
                    </label>
                </div>
                <span asp-validation-for="Password"></span>
            </div>

            <button type="submit" class="btn btn-primary btn-sm">Create</button>
        </form>
    </div>
</div>

<script>
    function myFunction() {
        var x = document.getElementById("myPassword");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>

UdemyNLayer_Project/UdemyNLayer_Project.Web/Views/Instructors/Update.cshtml
@model InstructorDto
@{
    ViewData["Title"] = "Create";
}

<figure class="text-center">
    <blockquote class="blockquote">
        <h2>Instructors</h2>
    </blockquote>
    <figcaption class="blockquote-footer mt-1">
        Update existing instructor page.
    </figcaption>
</figure>

<div class="container">
    <div class="row">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Name"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Surname" class="form-label">Surname</label>
                <input asp-for="Surname" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Surname"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Telephone" class="form-label">Telephone</label>
                <input asp-for="Telephone" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Telephone"></span>
            </div>

            <div class="mb-3">
                <label asp-for="About" class="form-label">Description</label>
                @Html.TextAreaFor(x => x.About, new { @class = "form-control col-md-6", rows = "4", cols = "4" })
                <span asp-validation-for="About"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Degree" class="form-label">Degree</label>
                <input asp-for="Degree" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Degree"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Mail" class="form-label">Mail</label>
                <input asp-for="Mail" type="text" class="form-control col-md-6" aria-describedby="emailHelp">
                <span asp-validation-for="Mail"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Password" class="form-label">Password</label>
                @Html.TextBoxFor(x => x.Password, new { @class = "form-control col-md-6", id = "myPassword" })
                <span asp-validation-for="Password"></span>
            </div>

            <button type="submit" class="btn btn-primary btn-sm">Update</button>
        </form>
    </div>
</div>

UdemyNLayer_Project/UdemyNLayer_Project.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UdemyNLayer Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Udemy Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructors" asp-action="Index">Instructor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - UdemyNLayer_Project.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />
    @RenderSection("Scripts", required: false)
</body>
</html>